[package]
name = "solidity-abi"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

[dependencies]
cfx-types = { workspace = true }
cfx-bytes = { workspace = true }
keccak-hash = { workspace = true }
solidity-abi-derive = { workspace = true }

[dev-dependencies]
lazy_static = { workspace = true }
rustc-hex = { workspace = true }
