[package]
name = "hibitset"
version = "0.6.0"
description = "Hierarchical bit set structure"
documentation = "https://docs.rs/hibitset"
repository = "https://github.com/slide-rs/hibitset"
keywords = ["bitset", "container", "data-structures", "hierarchical"]
categories = ["data-structures"]
license = "MIT/Apache-2.0"
authors = ["csheratt"]

[dependencies]
atom = "0.3"
malloc_size_of = {path = "../malloc_size_of" }
malloc_size_of_derive = {path = "../malloc_size_of_derive" }

[dependencies.rayon]
version = "1"
optional = true

[dev-dependencies]
rand = "0.7"

[features]
default = ["parallel"]
parallel = ["rayon"]
