[package]
name = "hibitset"
version = "0.6.0"
description = "Hierarchical bit set structure"
documentation = "https://docs.rs/hibitset"
repository = "https://github.com/slide-rs/hibitset"
keywords = ["bitset", "container", "data-structures", "hierarchical"]
categories = ["data-structures"]
license = "MIT/Apache-2.0"
authors = ["csheratt"]
edition = "2015" # TODO: fail if 2018

[dependencies]
atom = "0.3"
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }

[dependencies.rayon]
version = "1"
optional = true

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["parallel"]
parallel = ["rayon"]
