[package]
name = "cfx-rpc-eth-types"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cfx-types = { workspace = true }
thiserror = { workspace = true }
jsonrpc-core = "15.1.0"
primitives = { workspace = true }
cfxcore = { workspace = true }
rlp = { workspace = true }
cfx-parameters = { workspace = true }
alloy-rpc-types = { workspace = true }

