[package]
description = "Conflux consensus benchmark"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "consensus_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
cfxcore = { path = "../../crates/cfxcore/core", features = ["consensus_bench"]}
cfx-types = { path = "../../crates/cfx_types" }
primitives = { path = "../../crates/primitives" }
db = { path = "../../crates/dbs/db" }
threadpool = "1.7"
parking_lot = "0.12"
log4rs = { version = "1.4.0", features = ["background_rotation", "gzip"] }
log = "0.4"

[patch.crates-io]
# use a forked version to fix a vulnerability(introduced by failure) in vrf-rs, can be removed after the upstream is fixed
vrf = { git = "https://github.com/andrcmdr/vrf-rs.git", rev = "f7bdb21f7f5d1858a3bb0183f194440f9a4199b3" }
sqlite3-sys = { git = "https://github.com/Conflux-Chain/sqlite3-sys.git", rev = "1de8e5998f7c2d919336660b8ef4e8f52ac43844" }
