[package]
name = "schemadb"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem schemadb"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
once_cell = "1.7.2"
diem-logger = { workspace = true }
diem-metrics = { workspace = true }
rocksdb = { workspace = true }

[dev-dependencies]
byteorder = "1.4.3"
proptest = "1.0.0"
diem-temppath = { workspace = true }
