branches:
  only:
    - master
language: rust
matrix:
    include:
      # unit tests
      - env:
            - CACHE_NAME=unit_tests
        cache:
            timeout: 300
            cargo: true
        install:
            - export RUSTFLAGS="-D warnings"
            - cargo build --release
        script:
            - cargo test --release --all
      # benchmark tests
      - env:
            - CACHE_NAME=bench
        cache:
            timeout: 300
            cargo: true
        install:
            - export RUSTFLAGS="-g -D warnings"
        script:
            - cargo bench --all --no-run
      # integration tests
      - env:
            - CACHE_NAME=integration_tests
        cache:
            timeout: 300
            cargo: true
        before_install:
            # python3.6 is requried for integration tests.
            - pyenv install 3.6.2
            - pyenv global 3.6.2
            - ./dev-support/dep_pip3.sh
            # solc is required for integration tests to compile ERC20 contract.
            - wget -O solc https://github.com/ethereum/solidity/releases/download/v0.5.2/solc-static-linux
            - chmod +x solc
            - export PATH=$PATH:$PWD
        install:
            - export RUSTFLAGS="-g -D warnings"
            - cargo build --release
        script:
            - ./test/test_all.py
