[package]
name = "cfx-rpc-utils"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { workspace = true, features = ["jsonrpsee-types"] }
jsonrpc-core = { workspace = true }
cfx-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types = { workspace = true }
serde_json = { workspace = true }
alloy-sol-types = { workspace = true }
revm = { workspace = true }
thiserror = { workspace = true }
jsonrpsee-core = { workspace = true }
futures.workspace = true
tokio.workspace = true
cfx-tasks = { workspace = true }