[package]
name = "metrics"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.3"
parking_lot = "0.8"
timer = "0.2.0"
time = "0.1"
rand = "0.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false