[package]
name = "solidity-abi"
version = "0.1.0"
edition = "2018"


[dependencies]
cfx-types = {path = "../../cfx_types"}
keccak-hash = "0.5"

[dev-dependencies]
lazy_static = "1.4"
rustc-hex = "2.1"
