[package]
name = "cfx-rpc"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfx-rpc-eth-api = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
cfx-types = { workspace = true }
cfx-rpc-eth-types = { workspace = true }
cfx-rpc-primitives = { workspace = true }
cfx-rpc-cfx-impl = { workspace = true }
async-trait = { workspace = true }
keccak-hash = { workspace = true}
alloy-rpc-types = { workspace = true }
alloy-rpc-types-trace = { workspace = true }
cfxcore = { workspace = true }
primitives = { workspace = true }
geth-tracer = { workspace = true }
cfx-rpc-utils = { workspace = true }
parking_lot = { workspace = true }
cfx-rpc-cfx-types = { workspace = true }
jsonrpc-core = { workspace = true }
cfx-vm-types = { workspace = true }
cfx-statedb = { workspace = true }
cfx-executor = { workspace = true }
cfx-execute-helper = { workspace = true }
cfx-parameters = { workspace = true }
rustc-hex = { workspace = true }
transient-hashmap = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
cfx-util-macros = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
cfx-addr = { workspace = true }
solidity-abi = { workspace = true }
cfx-rpc-common-impl = { workspace = true }
cfx-tasks = { workspace = true}