[package]
description = "Conflux VM Interpreter"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "cfx-vm-interpreter"
version = "2.0.2"
edition = "2018"

[dependencies]
bit-set = "0.4"
cfx-bytes = { path = "../../cfx_bytes" }
cfx-types = { path = "../../cfx_types" }
cfx-vm-types = { path = "../vm-types" }
keccak-hash = "0.5"
lazy_static = "1.4"
log = "0.4"
malloc_size_of = {path = "../../util/malloc_size_of" }
memory-cache = { path = "../../util/memory-cache" }
parking_lot = "0.11"
rustc-hex = "2.1"

[dev-dependencies]
cfx-vm-types = { path = "../vm-types", features = ["testonly_code"] }
