[package]
name = "parity-version"
# NOTE: this value is used for OpenEthereum version string (via env CARGO_PKG_VERSION)
version = "3.3.3"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
license-file.workspace = true

[package.metadata]

[dependencies]
target_info = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
vergen = { workspace = true }
