[package]
description = "Conflux Account Management"
homepage = "http://conflux-chain.org"
license = "GPL-3.0"
name = "cfxcore-accounts"
version = "0.1.0"
authors = ["Conflux Foundation"]
edition = "2021"

[dependencies]
cfxkey = { workspace = true }
cfxstore = { workspace = true }
cfx-types = { workspace = true }
log = "0.4"
parking_lot = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempdir = { workspace = true }
