[package]
name = "treap-map"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# malloc_size_of_derive = {path = "../malloc_size_of_derive"}
malloc_size_of = {path = "../malloc_size_of"}
primitives = { path = "../../primitives" }
rand = "0.7"
rand_xorshift = "0.2"

[dev-dependencies]
rand_chacha = "0.2.1"
cfx-types = { path = "../../cfx_types" }
cfxkey = { path = "../../accounts/cfxkey" }
criterion = "0.3.0"

[[bench]]
name = "map_cmp"
harness = false