[package]
name = "diem-crypto"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-crypto"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bytes = { workspace = true }
curve25519-dalek = { version = "0.1.0", package = "curve25519-dalek-fiat", default-features = false, features = ["std"] }
digest = "0.9.0"
ed25519-dalek = { version = "0.1.0", package = "ed25519-dalek-fiat", default-features = false, features = ["std", "serde"] }
hex = "0.4.3"
hkdf = "0.10.0"
once_cell = "1.7.2"
mirai-annotations = "1.10.1"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.5.1", optional = true }
rand = "0.8.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_bytes = "0.11.5"
serde-name = "0.1.1"
sha2 = "0.9.3"
static_assertions = "1.1.0"
thiserror = "1.0.24"
tiny-keccak = { workspace = true, features = ["sha3"] }
x25519-dalek = { version = "0.1.0", package = "x25519-dalek-fiat", default-features = false, features = ["std"] }
aes-gcm = { workspace = true }
diem-crypto-derive = { workspace = true }
bcs = "0.1.2"
cfx-types = { workspace = true }
bls-signatures = { workspace = true }
vrf = { workspace = true }
lazy_static = { workspace = true }
parking_lot = { workspace = true }
openssl = "0.10"
diem-logger = { workspace = true }
pkcs8 = {version = "0.7.5", features = ["encryption", "std"]}


[dev-dependencies]
bitvec = "1.0.1"
proptest = "1.0.0"
proptest-derive = "0.5.1"
criterion = { workspace = true }
sha3 = "0.9.1"
serde_json = "1.0.64"
trybuild = "1.0.41"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(mirai)'] }

[features]
default = ["fiat"]
assert-private-keys-not-cloneable = []
cloneable-private-keys = []
fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]
fiat = ["curve25519-dalek/fiat_u64_backend", "ed25519-dalek/fiat_u64_backend", "x25519-dalek/fiat_u64_backend"]
u64 = ["curve25519-dalek/u64_backend", "ed25519-dalek/u64_backend", "x25519-dalek/u64_backend"]
u32 = ["curve25519-dalek/u32_backend", "ed25519-dalek/u32_backend", "x25519-dalek/u32_backend"]
batch = []

[[bench]]
name = "noise"
harness = false

[[bench]]
name = "ed25519"
harness = false

[[bench]]
name = "bls"
harness = false

[[bench]]
name = "vrf"
harness = false