[package]
description = "Conflux Stratum lib"
homepage = "https://www.confluxnetwork.org"
name = "cfx-stratum"
version = "1.12.0"
license = "GPL-3.0"
edition = "2021"

[dependencies]
cfx-types = { workspace = true }
keccak-hash = { workspace = true }
jsonrpc-core = "15.1.0"
jsonrpc-tcp-server = "15.1.0"
log = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
tokio02 = { workspace = true }
