[package]
name = "log-device"
version = "0.1.0"
edition = "2018"

[dependencies]
parking_lot = "0.10"
byteorder = "1.2.7"
db = { path = "../../db" }
rlp = "0.4.0"
rlp_derive = { git = "https://github.com/Conflux-Chain/conflux-parity-deps.git", rev = "1597a9cab02343eb2322ca0ac58d39b64e3f42d1"  }
kvdb = "0.4"
rand = "0.7"
