[package]
name = "log-device"
version = "0.1.0"
edition = "2018"

[dependencies]
parking_lot = "0.10"
byteorder = "1.2.7"
db = { path = "../../db" }
rlp = "0.4.0"
rlp_derive = { git = "https://github.com/Conflux-Chain/conflux-parity-deps.git" }
kvdb = "0.1.1"
rand = "0.7"
