[package]
description = "Conflux Runtime"
homepage = "http://conflux-chain.io"
license = "GPL-3.0"
name = "runtime"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures01 = { workspace = true }
tokio = "~0.1.9"