[package]
name = "diem-jellyfish-merkle"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem jellyfish merkle"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
byteorder = "1.4.3"
mirai-annotations = "1.10.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rand = { version = "0.8.3", optional = true }
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.24"

bcs = "0.1.2"
diem-crypto = { workspace = true }
diem-crypto-derive = { workspace = true }
diem-infallible = { workspace = true }
diem-metrics = { workspace = true }
diem-nibble = { workspace = true }
diem-types = { workspace = true }

[dev-dependencies]
rand = "0.8.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"

diem-crypto = { workspace = true, features = ["fuzzing"] }
diem-nibble = { workspace = true, features = ["fuzzing"] }
diem-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = [
    "proptest",
    "rand",
    "proptest-derive",
    "diem-crypto/fuzzing",
    "diem-types/fuzzing",
    "diem-nibble/fuzzing",
]
