[package]
name = "backup-service"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bytes = { workspace = true }
futures = { workspace = true }
hyper = "0.14.24"
once_cell = "1.7.2"
serde = { version = "1.0.124", default-features = false }
tokio = { workspace = true, features = ["full"] }
warp = "0.3.0"

bcs = "0.1.2"
diem-crypto = { workspace = true }
diem-logger = { workspace = true }
diem-metrics = { workspace = true }
diem-types = { workspace = true }
pos-ledger-db = { workspace = true }
storage-interface = { workspace = true }

[dev-dependencies]
pos-ledger-db = { workspace = true, features = ["fuzzing"] }
diem-config = { workspace = true }
diem-temppath = { workspace = true }

reqwest = { workspace = true, features = [
    "blocking",
    "json",
], default_features = false }

[features]
fuzzing = ["pos-ledger-db/fuzzing"]
