# bootnodes is a list of nodes that a conflux node trusts, and will be used to sync the blockchain when a node starts. 
# The value is a string divided by comma without space, and every entry is a node
# A node is identified by cfxnode://NODEID@PUBLICIP:PORT
# By default, no bootnodes are provided. What's provided here is a list of nodes that Conflux Team maintains across the world.

bootnodes="cfxnode://604deed272ec2a6f75538f0852e9cd71c616b35655ea8331b5987b3cc682097da76b9c8d2e90601d818acfac54f15af08a6389af245d4149d7d7f4a952bebfb3@39.97.223.148:32323,cfxnode://77bd8823c286e6b159432607d309983eac76830ecdd2bb2b6be7bf3b8e90bbae92f980dd7c8a6c284670679090d3ebf8e43ef91755cdf2eb6caa76532400be4c@182.92.92.126:32323,cfxnode://6582f6e20cfb975ff0b1fe6cb1d97f1e85c0502d44de441f43b032d7c8b986ebbd6a52f228ca55639b49742505bcf3f541551b2485d248e041d9ff1389bb016d@59.110.70.5:32323,cfxnode://24caea3455cf5ff9bbc532c6c6ca39b7edd0ecbbf29725dccdd36b5be629f1b0967391fdd99e81f9e35eb48a85602b2cff7c4c6893b7a906cc6b832c09ae9f33@101.201.127.86:32323,cfxnode://d2d4d2421da4b3b7314b83da06a2ed803965968ebc1614ac41eec5391a136d681a1433dbb56d067ad7e6cab682f35454a87a96e65a3b7eac867eea36b5d8535b@123.57.45.90:32323,cfxnode://ba297dc48bbba48e48c2f01dd0478d3a128b49ba4eccc65d0b800677bb8cc8a72eda57395f5a4b54269ec93189127efbd8ed235836db505f00b0e4558c1c6d97@39.97.208.206:32323,cfxnode://31f9397cfe1bbbecd5667dd13a5b6629201d5bdb9709813c8ad45e21a7ff767f17eb296ee635bb6c1265293bc4ad864db4ca229ad415d31e39121bf2a52405f9@13.229.52.100:32323,cfxnode://a7052f8b9d263549f737334b3cfe4d073fbedf69a21f25754a49a5cd7e83eb998eac1b223e55ae37779c1537bdd429719d0da45637d2d65dbaa917ad2c7085f2@20.43.79.41:32323,cfxnode://869ad83c0f6d8d9f571f62e444dd9a00bb5291e05b65b2d3920db912cdaaa9f283e72a5638ec71aadeeb37f53cdf40fb041214a80d7a6748f6ba96ec62b2909f@137.135.25.219:32323"

# Some preset develepment configurations.
# It should not be set in production environment.
#
# For both `test` and `dev` modes, we will
#     * Set initial difficulty to 4
#     * Allow calling test and debug rpc from public port
#
# `test` mode is for Conflux testing and debugging, we will
#     * Add latency to peer connections
#     * Skip handshake encryption check
#     * Skip header timestamp verification
#     * Handle NewBlockHash even in catch-up mode
#     * Allow data propagation test
#     * Allow setting genesis accounts and generate tx from secrets
#
# `dev` mode is for users to run a single node that automatically
#     generates blocks with fixed intervals
#     * Open port 12535 for ws rpc if `jsonrpc_ws_port` is not provided.
#     * Open port 12536 for tcp rpc if `jsonrpc_tcp_port` is not provided.
#     * Open port 12537 for http rpc if `jsonrpc_http_port` is not provided.
#     * generate blocks automatically without PoW if `start_mining` is false
#     * Skip catch-up mode even there is no peer
#
# mode = ""

# If you want to setup a single node running Conflux for development. You should
# COMMENT the bootnodes setting and you should use the following parameters:
#
# mode = "dev"

# Note that ``dev_block_interval_ms'' controls the mining rate in the dev mode.
#
# dev_block_interval_ms = 250

# ----------------- Mining Configuration -----------------

# `start_mining` controls whether a thread is started to mine new blocks.
# If not set, the node will not start mining blocks.
# If the value is true, `mining_author` must be set.
#
# start_mining=true

# `mining_author` is the address to receive mining rewards.
# The value is a 40-digit hex string without 0x prefix.
# By default, the value is not set.
#
# mining_author="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# `use_stratum` controls whether the mining process goes through the
# stratum protocol.
# use_stratum=true

# Listen address for stratum
#
# stratum_listen_address = "127.0.0.1"

# Port for stratum.
#
# stratum_port = 32525

# Secret key for stratum.
# The value is 64-digit hex string without 0x prefix.
# If not set, the RPC subscription will not check the authorization.
#
# stratum_secret = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# -------------- Log-related Configuration -------------

# `log_conf` the path of the log4rs configuration file. The configuration in the file will overwrite the value set by `log_level`.
# By default, the value is not set.
#
log_conf="log.yaml"

# `log_file` is the path of the log file"
# If not set, the log will only be printed to stdout, and not persisted to files.
# By default, the value is not set.
#
# log_file="conflux.log"

# `log_level` is the printed log level.
# The value should be one of "error", "warn", "info", "debug", "trace", "off"
#
# log_level="info"

# -------------- Network Configuration -------------

# `public_address` is the address of this node used for other nodes to connect to.
# If not set, the process will try to find out the public IP with best effort, and use `tcp_port` as public port.
# However, it's HIGHLY RECOMMENDED to set the value manually, especially for machines with IP translated by NAT.
#
# public_address="1.1.1.1"

# `tcp_port` is the TCP port that the process listens for P2P messages. The default is 32323.
#
# tcp_port=32323

# `public_tcp_port` is the public TCP port that other nodes should connect to. It might be different from 
# the tcp_port in case the machine is behind a NAT. The default is as same as `tcp_port`.
#
# public_tcp_port=32323

# `udp_port` is the UDP port used for node discovery.
# If not set, it will be the same as `port`.
#
# udp_port=32323

# `jsonrpc_http_keep_alive` is used to control whether to set KeepAlive for rpc HTTP connections.
#
# jsonrpc_http_keep_alive=false

# `jsonrpc_cors` is used to control the rpc domain validation policies.
# The value should be "none", "all", or a list string split by commas without space.
# If not set, domain validation is disabled.
# By default, the values are not set. 
#
# jsonrpc_cors="all"

# The following parameters are the ports for the node to provide rpc service. If not set,
# the node will not start rpc services. By default, the `jsonrpc_local_http_port` is set,
# so as to support the Conflux CLI subcommands. What's provided here is the recommended
# value if you want to start rpc services for other front-end applications.
# Note that to serve transaction-related RPCs, `persist_tx_index` should also be set to `true` or
# the node will only be able to handle very recent transactions.
#
# jsonrpc_ws_port=12535
# jsonrpc_tcp_port=12536
# jsonrpc_http_port=12537
# jsonrpc_local_tcp_port=12538
jsonrpc_local_http_port=12539

# --------------- Performance-related Network Parameters ----------------------

# Timeout for block-related requests (GetBlock, GetCmpctBlock, GetBlockTxn)
#
# blocks_request_timeout_ms = 20_000

# Time interval to check timeout requests periodically.
#
# check_request_period_ms=5000

# Chunk size for snapshot retrieval
#
# chunk_size_byte = 4194304

# Control whether to demote peers to unstrusted
#
# demote_peer_for_timeout = false

# Maximum network queue size. When reached, the queue will refuse any new data.
# The unit is MB.
#
# egress_queue_capacity = 256

# Minimum queue size for throttling in manner of ratio.
# The unit is MB.
#
# egress_min_throttle = 10

# Maximum queue size for throttling in manner of ratio.
# The unit is MB.
#
# egress_max_throttle = 10

# Time interval to to garbage-collect not block-graph-ready blocks periodically.
#
# expire_block_gc_period_s = 900

# Timeout for header-related requests (GetBlockHeaders)
#
# headers_request_timeout_ms=10_000

# Time interval to broadcast Status as heartbeat periodically
#
# heartbeat_period_interval_ms = 30_000

# Time to maintain transaction digests inflight status.
#
# inflight_pending_tx_index_maintain_timeout_ms = 30_000

# Maximum number of timeout allowed in `timeout_observing_period_s`.
# If the max is reached, the peer will be disconnected.
# `demote_peer_for_timeout` controls if the peer will be demoted in this case.
#
# max_allowed_timeout_in_observing_period = 10

# Maximum number of peers to download state chunks from.
#
# max_download_state_peers = 8

# Maximum number of handshaking sessions at the same time.
#
# max_handshakes = 64

# Maximum number of incoming connections.
#
# max_incoming_peers = 64

# Maximum number of outgoing connections.
#
# max_outgoing_peers = 16

# Maximum number of outgoing connections to archive nodes. 0 represents
# not required to connect to archive nodes. E.g. light node or full node
# need not to connect to archive nodes.
#
# max_outgoing_peers_archive = 0

# Maximum number of inflight requests for each peer.
# If the max is reached, requests will be buffered until inflight requests are responded or timeout.
#
# max_inflight_request_count = 64

# Maximum number of peers to broadcast transaction digests.
#
# max_peers_tx_propagation = 128

# Maximum cached received block size waiting to be processed.
#
# max_unprocessed_block_size_mb = 128

# Minimum number of peers to broadcast transaction digests.
#
# min_peers_tx_propagation = 8

# The time to maintain received transactions to avoid duplicated requests.
#
# received_tx_index_maintain_timeout_ms = 300_000

# Whether to request blocks with public key during catch-up to avoid recovering
# the public keys for transactions.
#
# request_block_with_public = false

# Time interval to broadcast transaction digests periodically.
#
# send_tx_period_ms = 1300

# Timeout for requesting snapshot candidate.
#
# snapshot_candidate_request_timeout_ms = 10_000

# Timeout for requesting snapshot chunks.
#
# snapshot_chunk_request_timeout_ms = 30_000

# Timeout for requesting snapshot manifests.
#
# snapshot_manifest_request_timeout_ms = 30_000

# `throttling_conf` is configuration file in TOML format to throttle RPCs, P2P messages.
# Throttling is enabled only when the parameter specified.
#
# throttling_conf="throttling.toml"

# The time period to observe if a peers has too many timeouts.
#
# timeout_observing_period_s = 600

# Timeout for transaction requests.
#
# transaction_request_timeout_ms = 30_000

# Time to maintain information of sent-out transactions for answering requests.
#
# tx_maintained_for_peer_timeout_ms = 600_000

# --------------- Peer Management Parameters -------------

# Timeout duration for refreshing discovery protocol when there are NOT enough outgoing connections.
#
# discovery_fast_refresh_timeout_ms = 10_000

# Timeout duration for initiating peer connection management.
#
# discovery_housekeeping_timeout_ms = 1_000

# Period between consecutive rounds of the same current discovery process.
#
# discovery_round_timeout_ms = 500

# `enable_discovery` is used to control whether the node will ask its neighbors for new peers
# and whether it will respond to other nodes' discovery requests.
#
# enable_discovery=true

# `netconf_dir` is the directory to store network related persistent data, including `net_key`,
# a list of trusted nodes and a list of untrusted nodes.
#
# netconf_dir="./net_config"

# `net_key` is the 256-bit private key to generate a unique node id for this node.
# The value is a 64-digit hex string without 0x prefix.
# If not set, the node will try to read from the file "key" under the directory `netconf_dir`.
# If the file is not found, the node will generate a random key.
# By default, the value is not set.
# If a node is restarted, it's suggested to keep the key unchanged.
#
# net_key="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# Timeout duration for persisting node table.
#
# node_table_timeout_s = 300

# Connection lifetime threshold for promotion.
#
# node_table_promotion_timeout_s = 259200


# `session_ip_limits` limits the number of TCP connections per IP address or subnet for security consideration.
# Its format is "n1,n2,n3,n4", where n1 is the quota of TCP connections for a single IP address, and n2/n3/n4
# are the quotas for subnet a/b/c. The default value is "1,8,4,2", which means:
#   1) Only 1 TCP connection allowed for a single IP address.
#   2) 8 TCP connections allowd for subnet a, e.g. 192.xxx.xxx.xxx/8
#   3) 4 TCP connections allowd for subnet b, e.g. 192.168.xxx.xxx/16
#   4) 2 TCP connections allowd for subnet c, e.g. 192.169.0.xxx/24
# Note, 0 represents unlimited.
#
# session_ip_limits="1,8,4,2"

# `subnet_quota` limits the number of nodes for a subnet B (e.g. 192.168.xxx.xxx/16) stored in database.
# Nodes in database are used to establish outgoing TCP connections for P2P communications.
# Note, 0 represents unlimited.
#
# subnet_quota=32

# ---------------- Transaction Cache Parameters -----------------

# Whether to persist transaction indices.
# This only needs to be enabled if you want to reliably answer transaction-related RPCs.
#
# persist_tx_index = false

# Time to keep transactions in in-memory transaction cache.
#
# tx_cache_index_maintain_timeout_ms = 300_000

# Maximum number of transactions allowed in the transaction pool.
#
# tx_pool_size = 500_000

# Minimum allowed transaction gas price in the transaction pool.
#
# tx_pool_min_tx_gas_price = 1

# ------------------ Storage Parameters ----------------------

# The number of additional snapshot before the current stable checkpoint that we will maintain.
# If it's 0, all snapshot before stable genesis will be deleted and the states are unavailable.
#
# additional_maintained_snapshot_count = 0

# Time interval to evict old data from in-memory data cache.
#
# block_cache_gc_period_ms = 5_000

# Database type to store block-related data.
# Supported: rocksdb, sqlite.
#
# block_db_type = "rocksdb"

# The root directory of all data (block data, state data, log files, node database).
#
# conflux_data_dir = "./"

# The directory to store block-related data.
#
# db_dir = "./blockchain_db"

# Maximum size of cached ledger data (block, receipts, e.t.c.)
# The unit is MB.
#
# ledger_cache_size = 1024

# Rocksdb cache size.
# Only applies if `block_db_type = "rocksdb"`.
#
# rocksdb_cache_size = 128

# Rocksdb compaction file path.
# Only applies if `block_db_type = "rocksdb"`.
# If not set, compaction configuration will be set automatically by rocksdb.
#
# rocksdb_compaction_profile = "./compact_file.conf"

# State storage parameters.
# Refer to the documentation for details.
#
# storage_delta_mpts_cache_recent_lfu_factor=4.0
# storage_delta_mpts_cache_size=20000000
# storage_delta_mpts_cache_start_size=1000000
# storage_delta_mpts_node_map_vec_size=80000000
# storage_delta_mpts_slab_idle_size=200000

# -------------------- Others -------------------

# Whether to allow execution without deferring if the execution thread is idle.
#
# enable_optimistic_execution = true

# Maximum number of blocks whose timestamp is in the near future is maintained in memory.
#
# future_block_buffer_capacity = 32768

# Maximum number of log entries returned from cfx_getLogs.
# If not set, cfx_getLogs will not limit the number of logs returned.
#
# get_logs_filter_max_limit = 10

# Epoch batch size used in log filtering.
# Larger batch sizes may improve performance but might also prevent consensus from making progress under high RPC load.
#
# get_logs_epoch_batch_size = 128

# Maximum number of transactions allowed for peers to send to a catch-up node.
#
# max_trans_count_received_in_catch_up = 60_000

# The chain_id of conflux network
# 1 for testnet
# commentting out for not verify chain_id
#
chain_id = 1
