# bootnodes is a list of nodes that a conflux node trusts, and will be used to sync the blockchain when a node starts. 
# The value is a string divided by comma without space, and every entry is a node
# A node is identified by cfxnode://NODEID@PUBLICIP:PORT
# By default, no bootnodes are provided. What's provided here is a list of nodes that Conflux Team maintains across the world.

bootnodes="cfxnode://72d0736cc9fffc21306f097b8ce5099f62d72ec05bd94ceff5bd6ec6783801f2f7ad17a16f57499243925ed9633654081d3b4cb95bab7474144e92ffe39c9cc4@52.175.52.111:32323,cfxnode://4eb526348481292722188664543d3dc80a5f2a35b578b2d72d54293ccc400fa87efb69e728dc56ef924be708ec8b33fa3648eca2a81e9e95f44cd0b3252fea77@13.67.73.51:32323,cfxnode://5ec498fd7c8ff5389024f6a6e80ed75539c89dda8e655cae48c8ae883590acb940d856a601e7f788d5a2cf417eb5dee0fa9ae6c0a2ac8e6d8253cb7ac986a651@137.135.25.219:32323,cfxnode://9a3b64f2652fe73d573fa7bd877f4f02f96fbc4e2287731b59d0350f80a4a2437f43cd067096b0b3afd6e14a5af5929c9719afe42fd42c1143deea9942fc6d38@23.96.108.96:32323,cfxnode://9991bd3f5d0e614a3fcc8640fdfcbefbc0e95de7fa68baff4cb95f8614fa162b080a497bca5037196920bf68ed2554605f29b38ba2390b4bc8de91dac91eab34@13.69.186.42:32323,cfxnode://ce6c447f1e6f8e43e07f9ee8d5b49180663ad934f7fffa0db654e69522a234628f966fc8ea0285c4357285885f188804ae09b5303a6c8e627149c2a41d5156a3@13.69.98.59:32323,cfxnode://448839f2900f4a22ce611bd66a4fc93f8fa02a4b185679ba89078c0bf9c6c9328d3df77c4c8451fca12f2a8daab53b8f38762c14d6f24ba6897a9ddd79988474@65.52.200.134:32323,cfxnode://54e1d46b03527d79986e3c884e6ef6cec09cfc548f7ad20d8f0c996396cbe04bead6f689822eae2ab78b08e2be360371679d94f41fc75645ae166c557c3cd7e4@13.66.22.178:32323,cfxnode://b98efb859fd2c9d88f9c5f7bf0da8a554a277e79122517ba7adf4f4bee8f5d99950c4f794aeb67b170f26faacaf0a5f4e953270c070c24a56de8e7939c578fef@23.101.127.200:32323,cfxnode://dc79bc70833e797ba41eff5bda67c0484abca4918ef38289b5f96acd3daa890eadc85d46fc71f250a8ac51b0c4ab70b3812b1ed3c8f10a9e996b6663be34f1f1@52.167.49.216:32323,cfxnode://bd173908d52a2a991aae86c3bc0453b7019c44233c5f2ed6241fc8e5a43689abf812266e8bb581470a5cb55fceeae1e4c8020baa61b8f2b2371a259fccb5b544@20.43.79.41:32323,cfxnode://012d0f7e59f62220e2a90e458cf0d65e5690d09dad59ce05f03f5878a7142bef9f412decdbefa7716e8331e94d68f05c2ce943db4ffa5440e496f2130d3feb50@13.70.109.39:32323,cfxnode://4d2730a33e1e06f02606343c19c60ec28d191004f558085ed01ad752d2a45c54e88c99908dc932b69ee433ae2f74753b32dbb3ac89024f593c645579a763560b@40.127.68.228:32323,cfxnode://7e2e4918d3aff819afdb8782c13544ea63193d82d9529dfbab3efb101754b322fc161c771a784e1b0420da8f78dbb127fbac24d1d626b634b462542ad8953bd7@13.88.227.15:32323,cfxnode://f94343e4c806b2968c5e4bf4cbc49736d04af03fab4b797bc11aea2af2cb23d706d1d9c5dfae430a2df1d7fe6a6a988aff43c50898dc087161e51fa69d603997@13.66.212.46:32323,cfxnode://8c460046bbc9f534d79344024a444910525b832eb7b268c0cd11b26c57a6b40290f5f64c9431d47af4763bb950173b172780a4894f8aa45a90db08780ec3d179@51.140.46.12:32323,cfxnode://8949669b26e015acd6c3e1ba5f87e2a7242a8611eec224428d5553005e45b4c6b2e352721be6334a445340441c8d6f8dfeab20472fbb0ce9733c293f0c1c781c@52.231.28.50:32323,cfxnode://cadd4aabb35be7edbd1c8e60131c90eb9cec502a3565234190b7922922007838caf6556fb32e3e53fd98510f789a505b68db4c95899d6b29e206c7ad3f87b106@52.231.162.167:32323,cfxnode://207129bba501e6a0aa8be66421dfc9984ff08d9d2d14f24c4db651b3e90ef77d5315ab4f49ef7a62208d9596c87248b6e7bf25886e36e2a79a0ae72275149397@52.143.177.113:32323,cfxnode://7d7e433ed0b1ce6c9618b841ec11526348bc2750cd600f4fa3640d8139c230bfadb4178c92f34b507a95826e0c05b42594bab7d4bc4f581194bab91ab7a71584@40.127.0.99:32323,cfxnode://7ffff7f14f8f73fa93a95309803bbc93c762c48bc873a823ac40500471ce2e3ff5b5af36c5c7f0bef47cec4e284c40ec976620b6941ec927b00891abc0646a65@47.93.241.217:32323,cfxnode://47bd00bed8e39e51fc94edca067cf7a0d23c67689841a5e9437e51f430c98e463b6caf0d8bed2576393620efabee2a531902938759d92ee289a4d8ae8277d254@39.107.127.68:32323,cfxnode://bde628101fa224422b484ff7cdc4483aa4185c98cdf74ff11b20c0cbe5075dae8dbb2edb0a60f22d94f78003df4b2f08f942c7b1d4b78404a083e46ee5d78aee@123.56.97.171:32323"

# `public_address` is the address of this node used for other nodes to connect to.
# If not set, the process will try to find out the public IP with best effort, and use `port` as public port.
# However, it's HIGHLY RECOMMENDED to set the value manually, especially for machines with IP translated by NAT.
#
public_address="59.66.209.32:32323"

# `port` is the TCP port that the process listens for P2P messages.
#
# port=32323

# `udp_port` is the UDP port used for node discovery. 
# If not set, it will be the same as `port`.
#
# udp_port=32323

# `start_mining` controls whether a thread is started to mine new blocks.
# If not set, the node will not start mining blocks.
# If the value is true, `mining_author` must be set.
#
# start_mining=true

# `mining_author` is the address to receive mining rewards.
# The value is a 40-digit hex string without 0x prefix.
# By default, the value is not set.
#
# mining_author="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# `jsonrpc_tcp_port` and `jsonrpc_http_port` are the ports for the node to
# provide rpc service. If not set, the node will not start rpc services. By
# default, the values are not set. What's provided here is the recommended value
# if you want to start rpc services for other front-end applications.
#
# jsonrpc_tcp_port=12536
# jsonrpc_http_port=12537



# The following parameters do not need to be changed in normal cases.

# `net_key` is the 256-bit private key to generate a unique node id for this node.
# The value is a 64-digit hex string without 0x prefix.
# If not set, the node will try to read from the file "key" under the directory `netconf_dir`.
# If the file is not found, the node will generate a random key.
# By default, the value is not set.
# If a node is restarted, it's suggested to keep the key unchanged.
#
# net_key="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# `netconf_dir` is the directory to store network related persistent data, including `net_key`, a list of trusted nodes and a list of untrusted nodes.
# 
# netconf_dir="./net_config"

# `db_dir` is the directory to store blockchain database.
#
# db_dir="./blockchain_db"

# `log_level` is the printed log level.
# The value should be one of "error", "warn", "info", "debug", "trace", "off"
# 
# log_level="info"

# `log_file` is the path of the log file"
# If not set, the log will only be printed to stdout, and not persisted to files.
# By default, the value is not set.
#
# log_file="conflux.log"

# `log_conf` the path of the log4rs configuration file. The configuration in the file will overwrite the value set by `log_level`.
# By default, the value is not set.
#
log_conf="log.yaml"

# `enable_discovery` is used to control whether the node will ask its neighbors for new peers and whether it will respond to other nodes' discovery requests.
#
# enable_discovery=true

# `jsonrpc_http_keep_alive` is used to control whether to set KeepAlive for rpc HTTP connections.
#
# jsonrpc_http_keep_alive=false

# `jsonrpc_cors` is used to control the rpc domain validation policies.
# The value should be "none", "all", or a list string split by commas without space.
# If not set, domain validation is disabled.
# By default, the values are not set. 
#
# jsonrpc_cors="all"

# The following parameters control the max memory usage of the node. 
# The default values are optimized for 16GB RAM.
# Roughly speaking, if you want to reduce the max memory consumption by half, just set every value to half of its default value. 
# But the performance downgrade may cause the node unable to catch up with a blockchain running 3000 tps workload.
#
# ledger_cache_size=2048
# db_cache_size=128
# storage_cache_start_size=1000000
# storage_cache_size=20000000
# storage_recent_lfu_factor=4.0
# storage_idle_size=200000
# storage_node_map_size=80000000
# tx_pool_size=500_000

# The following are the timeout parameters.
#
# node_table_timeout=300
# node_table_promotion_timeout=2592000
# send_tx_period_ms=1300
# check_request_period_ms=5000
# block_cache_gc_period_ms=5000
# headers_request_timeout_ms=10_000
# blocks_request_timeout_ms=30_000
# transaction_request_timeout_ms=30_000
# tx_maintained_for_peer_timeout_ms=600_000
# max_inflight_request_count=64
# received_tx_index_maintain_timeout_ms=600_000
# max_trans_count_received_in_catch_up=60000
# request_block_with_public=false

# IP/Subnet policy configurations

# `session_ip_limits` limits the number of TCP connections per IP address or subnet for security consideration.
# Its format is "n1,n2,n3,n4", where n1 is the quota of TCP connections for a single IP address, and n2/n3/n4 
# are the quotas for subnet a/b/c. The default value is "1,8,4,2", which means:
#   1) Only 1 TCP connection allowed for a single IP address.
#   2) 8 TCP connections allowd for subnet a, e.g. 192.xxx.xxx.xxx/8
#   3) 4 TCP connections allowd for subnet b, e.g. 192.168.xxx.xxx/16
#   4) 2 TCP connections allowd for subnet c, e.g. 192.169.0.xxx/24
# Note, 0 represents unlimited.
# 
# session_ip_limits="1,8,4,2"

# `subnet_quota` limits the number of nodes for a subnet B (e.g. 192.168.xxx.xxx/16) stored in database.
# Nodes in database are used to establish outgoing TCP connections for P2P communications.
# Note, 0 represents unlimited.
#
# subnet_quota=32
