[package]
name = "consensus-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
mirai-annotations = { version = "1.10.1", default-features = false }
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.124", default-features = false }

executor-types = { workspace = true }
bcs = "0.1.2"
diem-crypto = { workspace = true }
diem-crypto-derive = { workspace = true }
diem-infallible = { workspace = true }
diem-types = { workspace = true }
short-hex-str = { workspace = true }
rustc-hex = { workspace = true }


[dev-dependencies]
proptest = "1.0.0"

diem-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "diem-types/fuzzing", "diem-crypto/fuzzing"]
