[package]
name = "memory-cache"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "An LRU-cache which operates on memory used"
license = "GPL3"
edition = "2021"

[dependencies]
malloc_size_of = { workspace = true }
lru-cache = { workspace = true }
