[package]
name = "kvdb-rocksdb"
version = "0.1.4"
repository = "https://github.com/paritytech/parity-common"
description = "kvdb implementation backed by rocksDB"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
fs-swap = "0.2.4"
interleaved-ordered = "0.1.0"
kvdb = {git="https://github.com/paritytech/parity-common.git", branch="ao-upstream-rocksdb", version = "0.2"}
log = "0.4"
num_cpus = "1.0"
parking_lot = "0.8"
regex = "1.0"
cfx-types = { path = "../../../cfx_types" }

[dependencies.rocksdb]
version = "0.12"
default-features = false
features = ["snappy"]

[dev-dependencies]
tempdir = "0.3"
ethereum-types = "0.7"
