[package]
name = "diem-config"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-config"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
if-addrs = "0.14.0"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["rc"], default-features = false }
yaml_serde = "0.10.3"
thiserror = "1.0.24"

bcs = "0.1.2"
diem-crypto = { workspace = true }
diem-global-constants = { workspace = true }
diem-logger = { workspace = true }
diem-secure-storage = { workspace = true }
diem-temppath = { workspace = true }
diem-types = { workspace = true }
short-hex-str = { workspace = true }
cfx-types = { workspace = true }

[dev-dependencies]
diem-crypto = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["diem-crypto/fuzzing", "diem-types/fuzzing"]
testing = []
