[package]
name = "throttling"
version = "0.1.0"
edition = "2018"

[dependencies]
parking_lot = "0.10"
toml = "0.4"
malloc_size_of = {path = "../../util/malloc_size_of"}
malloc_size_of_derive = {path = "../../util/malloc_size_of_derive"}